// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Editor 描述一个系统上可用的文本编辑器。
 */
export class Editor {
    "id": string;
    "name": string;
    "path": string;

    /** Creates a new Editor instance. */
    constructor($$source: Partial<Editor> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Editor instance from a string or object.
     */
    static createFrom($$source: any = {}): Editor {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Editor($$parsedSource as Partial<Editor>);
    }
}
